name: Assignment Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "assignment/ui/**"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Frontend
        run: docker build -t inventory-ui ./assignment/ui

      - name: Run and Verify
        run: |
          docker run -d --name ui-test inventory-ui
          sleep 3
          docker logs ui-test 2>&1 | grep "test is successful"

          docker exec ui-test ls /usr/share/nginx/html/index.html

      - name: Cleanup
        if: always()
        run: docker rm -f ui-test
