name: Assignment Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "assignment/ui/**"
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Frontend
        run: docker build -t inventory-ui ./assignment/ui

      - name: Run and Verify
        run: |
          docker run -d --name ui-test inventory-ui

          echo "Checking if index.html exists in the container..."
          docker exec ui-test ls /usr/share/nginx/html/index.html

          echo "Checking if nginx config was replaced..."
          docker exec ui-test cat /etc/nginx/conf.d/default.conf | grep "upstream app"

      - name: Cleanup
        if: always()
        run: docker rm -f ui-test
